// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CommentVotes string
	Comments     string
	PostVotes    string
	Posts        string
	Users        string
}{
	CommentVotes: "comment_votes",
	Comments:     "comments",
	PostVotes:    "post_votes",
	Posts:        "posts",
	Users:        "users",
}
